app:
  name: account-api
  namespace: cesi-eats
  image:
    repository: ghcr.io/cesi-eats/account_api
    tag: latest

dependencies:
  lapinou:
    uri: amqp://rabbitmq-service.cesi-eats.svc.cluster.local:5672

  database:
    host: armanddebesse.fr
    port: 5432
    username: root
    password: password
    database_name: account_db