apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-env-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
    LAPINOU_URI: {{ .Values.dependencies.lapinou.uri }}
    DB_HOST: {{ .Values.dependencies.postgres.host }}
    DB_PORT: {{ .Values.dependencies.postgres.port }}
    DB_USERNAME: {{ .Values.dependencies.postgres.username }}
    DB_PASSWORD: {{ .Values.dependencies.postgres.password }}
    DB_NAME: {{ .Values.dependencies.postgres.database }}